version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: Octokit
    versions:
    - 0.48.0
    - 0.49.0
  - dependency-name: nunit
    versions:
    - 3.13.0
    - 3.13.1
  - dependency-name: coverlet.msbuild
    versions:
    - 3.0.2
  - dependency-name: Lucene.Net.QueryParser
    versions:
    - 4.8.0-beta00013
  - dependency-name: Lucene.Net.Analysis.Common
    versions:
    - 4.8.0-beta00013
  - dependency-name: Lucene.Net
    versions:
    - 4.8.0-beta00013
