version: 0.1.{build}
image: Visual Studio 2017
environment:
  MSBUILD_LOG_VERSION: 2.0.94
  MSBUILD_LOG_FILE: msbuild.binlog
  NUGET_VERBOSITY: quiet
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  # This might be causing a hang.
  # account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore -Verbosity %NUGET_VERBOSITY%
- cmd: choco install codecov
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
test_script:
  - cmd: dotnet test --no-build --logger trx
after_test:
- cmd: codecov -f "coverage.opencover.xml"
- ps: Get-ChildItem -Recurse *.trx | %{ Invoke-WebRequest -uri "https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)" -Method POST -Infile $_.FullName -ContentType 'application/xml' -Verbose 
artifacts:
  - path: $(MSBUILD_LOG_FILE)
    name: MSBuild Binary Log
    type: file
deploy:
  - provider: NuGet
    api_key:
      secure: lJITXIl3n0A7VLVoNNI8kI0Ay/e5XliMI2CtZS8L6T6K50r0PZlRZ5IgSdKzWQ+c
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      branch: [
        master
      ]