version: 0.1.{build}
image: Visual Studio 2017
environment:
  MSBUILD_LOG_VERSION: 2.0.94
  MSBUILD_LOG_FILE: msbuild.binlog
  NUGET_VERBOSITY: quiet
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  # This might be causing a hang.
  # account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore -Verbosity %NUGET_VERBOSITY%
- cmd: nuget install MSBuild.StructuredLogger -Version %MSBUILD_LOG_VERSION%  -SolutionDirectory . -Verbosity %NUGET_VERBOSITY%
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
artifacts:
  - path: $(MSBUILD_LOG_FILE)
    name: MSBuild Binary Log
    type: file