version: 0.1.{build}
image: Visual Studio 2017
environment:
  DOCFX_FOLDER: _site
  MSBUILD_LOG_FILE: msbuild.binlog
  NUGET_VERBOSITY: quiet
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: nuget restore -Verbosity %NUGET_VERBOSITY%
- cmd: choco install codecov
- cmd: choco install docfx
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
after_build:
- cmd: docfx
test_script:
  - cmd: dotnet test --no-build --logger trx #override default test command to one that respects msbuild.rsp
after_test:
- cmd: codecov -f "coverage.opencover.xml"
- ps: .\scripts\appveyor\Publish-TestResults.ps1
    
artifacts:
  - path: $(DOCFX_FOLDER)
    name: Documentation
    type: Zip
  - path: $(MSBUILD_LOG_FILE)
    name: MSBuild Binary Log
    type: File
  - path: coverage.opencover.xml
    name: CodeCov.IO Report
    type: File
  - path: '**/*.trx'
    name: Test Results
    type: File
deploy:
  - provider: NuGet
    api_key:
      secure: lJITXIl3n0A7VLVoNNI8kI0Ay/e5XliMI2CtZS8L6T6K50r0PZlRZ5IgSdKzWQ+c
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      branch: [ master ]